services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: user_art
      POSTGRES_PASSWORD: 1324
      PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres_articles:/var/lib/postgresql/data


volumes:
  postgres_articles: