services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres_articles:/var/lib/postgresql/data

volumes:
  postgres_articles: