"""add field conf_reg_link

Revision ID: 0003
Revises: 0002
Create Date: 2025-04-06 19:21:18.469609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('conf_reg_link', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_conf_reg_link'), 'users', ['conf_reg_link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_conf_reg_link'), table_name='users')
    op.drop_column('users', 'conf_reg_link')
    # ### end Alembic commands ###
